version: '3.0'

services:
  grafana:
    container_name: 'grafana-bigquery-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.2.3}
    cap_add:
      - SYS_PTRACE
      - ALL
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000/tcp
      - 3222:3222

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-bigquery-datasource
      - ./:/build
      - ./provisioning:/etc/grafana/provisioning
